/**
 * Autogenerated by Thrift Compiler (0.16.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef HelloSvc_H
#define HelloSvc_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include <memory>
#include "hello_types.h"



#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class HelloSvcIf {
 public:
  virtual ~HelloSvcIf() {}
  virtual void hello_func(std::string& _return) = 0;
};

class HelloSvcIfFactory {
 public:
  typedef HelloSvcIf Handler;

  virtual ~HelloSvcIfFactory() {}

  virtual HelloSvcIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(HelloSvcIf* /* handler */) = 0;
  };

class HelloSvcIfSingletonFactory : virtual public HelloSvcIfFactory {
 public:
  HelloSvcIfSingletonFactory(const ::std::shared_ptr<HelloSvcIf>& iface) : iface_(iface) {}
  virtual ~HelloSvcIfSingletonFactory() {}

  virtual HelloSvcIf* getHandler(const ::apache::thrift::TConnectionInfo&) override {
    return iface_.get();
  }
  virtual void releaseHandler(HelloSvcIf* /* handler */) override {}

 protected:
  ::std::shared_ptr<HelloSvcIf> iface_;
};

class HelloSvcNull : virtual public HelloSvcIf {
 public:
  virtual ~HelloSvcNull() {}
  void hello_func(std::string& /* _return */) override {
    return;
  }
};


class HelloSvc_hello_func_args {
 public:

  HelloSvc_hello_func_args(const HelloSvc_hello_func_args&) noexcept;
  HelloSvc_hello_func_args& operator=(const HelloSvc_hello_func_args&) noexcept;
  HelloSvc_hello_func_args() noexcept {
  }

  virtual ~HelloSvc_hello_func_args() noexcept;

  bool operator == (const HelloSvc_hello_func_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const HelloSvc_hello_func_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const HelloSvc_hello_func_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class HelloSvc_hello_func_pargs {
 public:


  virtual ~HelloSvc_hello_func_pargs() noexcept;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _HelloSvc_hello_func_result__isset {
  _HelloSvc_hello_func_result__isset() : success(false) {}
  bool success :1;
} _HelloSvc_hello_func_result__isset;

class HelloSvc_hello_func_result {
 public:

  HelloSvc_hello_func_result(const HelloSvc_hello_func_result&);
  HelloSvc_hello_func_result& operator=(const HelloSvc_hello_func_result&);
  HelloSvc_hello_func_result() noexcept
                             : success() {
  }

  virtual ~HelloSvc_hello_func_result() noexcept;
  std::string success;

  _HelloSvc_hello_func_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const HelloSvc_hello_func_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const HelloSvc_hello_func_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const HelloSvc_hello_func_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _HelloSvc_hello_func_presult__isset {
  _HelloSvc_hello_func_presult__isset() : success(false) {}
  bool success :1;
} _HelloSvc_hello_func_presult__isset;

class HelloSvc_hello_func_presult {
 public:


  virtual ~HelloSvc_hello_func_presult() noexcept;
  std::string* success;

  _HelloSvc_hello_func_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class HelloSvcClient : virtual public HelloSvcIf {
 public:
  HelloSvcClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  HelloSvcClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void hello_func(std::string& _return) override;
  void send_hello_func();
  void recv_hello_func(std::string& _return);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class HelloSvcProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::std::shared_ptr<HelloSvcIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext) override;
 private:
  typedef  void (HelloSvcProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_hello_func(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  HelloSvcProcessor(::std::shared_ptr<HelloSvcIf> iface) :
    iface_(iface) {
    processMap_["hello_func"] = &HelloSvcProcessor::process_hello_func;
  }

  virtual ~HelloSvcProcessor() {}
};

class HelloSvcProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  HelloSvcProcessorFactory(const ::std::shared_ptr< HelloSvcIfFactory >& handlerFactory) noexcept :
      handlerFactory_(handlerFactory) {}

  ::std::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo) override;

 protected:
  ::std::shared_ptr< HelloSvcIfFactory > handlerFactory_;
};

class HelloSvcMultiface : virtual public HelloSvcIf {
 public:
  HelloSvcMultiface(std::vector<std::shared_ptr<HelloSvcIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~HelloSvcMultiface() {}
 protected:
  std::vector<std::shared_ptr<HelloSvcIf> > ifaces_;
  HelloSvcMultiface() {}
  void add(::std::shared_ptr<HelloSvcIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void hello_func(std::string& _return) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->hello_func(_return);
    }
    ifaces_[i]->hello_func(_return);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class HelloSvcConcurrentClient : virtual public HelloSvcIf {
 public:
  HelloSvcConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(prot);
  }
  HelloSvcConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void hello_func(std::string& _return) override;
  int32_t send_hello_func();
  void recv_hello_func(std::string& _return, const int32_t seqid);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif



#endif
