/**
 * Autogenerated by Thrift Compiler (0.16.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef TTGService_H
#define TTGService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include <memory>
#include "TTG_types.h"

namespace TTG {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class TTGServiceIf {
 public:
  virtual ~TTGServiceIf() {}
  virtual void getStudentInfo(Response& _return, const Request& request) = 0;
};

class TTGServiceIfFactory {
 public:
  typedef TTGServiceIf Handler;

  virtual ~TTGServiceIfFactory() {}

  virtual TTGServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(TTGServiceIf* /* handler */) = 0;
  };

class TTGServiceIfSingletonFactory : virtual public TTGServiceIfFactory {
 public:
  TTGServiceIfSingletonFactory(const ::std::shared_ptr<TTGServiceIf>& iface) : iface_(iface) {}
  virtual ~TTGServiceIfSingletonFactory() {}

  virtual TTGServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) override {
    return iface_.get();
  }
  virtual void releaseHandler(TTGServiceIf* /* handler */) override {}

 protected:
  ::std::shared_ptr<TTGServiceIf> iface_;
};

class TTGServiceNull : virtual public TTGServiceIf {
 public:
  virtual ~TTGServiceNull() {}
  void getStudentInfo(Response& /* _return */, const Request& /* request */) override {
    return;
  }
};

typedef struct _TTGService_getStudentInfo_args__isset {
  _TTGService_getStudentInfo_args__isset() : request(false) {}
  bool request :1;
} _TTGService_getStudentInfo_args__isset;

class TTGService_getStudentInfo_args {
 public:

  TTGService_getStudentInfo_args(const TTGService_getStudentInfo_args&) noexcept;
  TTGService_getStudentInfo_args& operator=(const TTGService_getStudentInfo_args&) noexcept;
  TTGService_getStudentInfo_args() noexcept {
  }

  virtual ~TTGService_getStudentInfo_args() noexcept;
  Request request;

  _TTGService_getStudentInfo_args__isset __isset;

  void __set_request(const Request& val);

  bool operator == (const TTGService_getStudentInfo_args & rhs) const
  {
    if (!(request == rhs.request))
      return false;
    return true;
  }
  bool operator != (const TTGService_getStudentInfo_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TTGService_getStudentInfo_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class TTGService_getStudentInfo_pargs {
 public:


  virtual ~TTGService_getStudentInfo_pargs() noexcept;
  const Request* request;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TTGService_getStudentInfo_result__isset {
  _TTGService_getStudentInfo_result__isset() : success(false) {}
  bool success :1;
} _TTGService_getStudentInfo_result__isset;

class TTGService_getStudentInfo_result {
 public:

  TTGService_getStudentInfo_result(const TTGService_getStudentInfo_result&);
  TTGService_getStudentInfo_result& operator=(const TTGService_getStudentInfo_result&);
  TTGService_getStudentInfo_result() noexcept {
  }

  virtual ~TTGService_getStudentInfo_result() noexcept;
  Response success;

  _TTGService_getStudentInfo_result__isset __isset;

  void __set_success(const Response& val);

  bool operator == (const TTGService_getStudentInfo_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const TTGService_getStudentInfo_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TTGService_getStudentInfo_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TTGService_getStudentInfo_presult__isset {
  _TTGService_getStudentInfo_presult__isset() : success(false) {}
  bool success :1;
} _TTGService_getStudentInfo_presult__isset;

class TTGService_getStudentInfo_presult {
 public:


  virtual ~TTGService_getStudentInfo_presult() noexcept;
  Response* success;

  _TTGService_getStudentInfo_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class TTGServiceClient : virtual public TTGServiceIf {
 public:
  TTGServiceClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  TTGServiceClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void getStudentInfo(Response& _return, const Request& request) override;
  void send_getStudentInfo(const Request& request);
  void recv_getStudentInfo(Response& _return);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class TTGServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::std::shared_ptr<TTGServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext) override;
 private:
  typedef  void (TTGServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_getStudentInfo(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  TTGServiceProcessor(::std::shared_ptr<TTGServiceIf> iface) :
    iface_(iface) {
    processMap_["getStudentInfo"] = &TTGServiceProcessor::process_getStudentInfo;
  }

  virtual ~TTGServiceProcessor() {}
};

class TTGServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  TTGServiceProcessorFactory(const ::std::shared_ptr< TTGServiceIfFactory >& handlerFactory) noexcept :
      handlerFactory_(handlerFactory) {}

  ::std::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo) override;

 protected:
  ::std::shared_ptr< TTGServiceIfFactory > handlerFactory_;
};

class TTGServiceMultiface : virtual public TTGServiceIf {
 public:
  TTGServiceMultiface(std::vector<std::shared_ptr<TTGServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~TTGServiceMultiface() {}
 protected:
  std::vector<std::shared_ptr<TTGServiceIf> > ifaces_;
  TTGServiceMultiface() {}
  void add(::std::shared_ptr<TTGServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void getStudentInfo(Response& _return, const Request& request) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->getStudentInfo(_return, request);
    }
    ifaces_[i]->getStudentInfo(_return, request);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class TTGServiceConcurrentClient : virtual public TTGServiceIf {
 public:
  TTGServiceConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(prot);
  }
  TTGServiceConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void getStudentInfo(Response& _return, const Request& request) override;
  int32_t send_getStudentInfo(const Request& request);
  void recv_getStudentInfo(Response& _return, const int32_t seqid);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

} // namespace

#endif
